// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Navbar() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav id=\"navbar-main\" class=\"navbar is-fixed-top\"><div class=\"navbar-brand\"><a class=\"navbar-item is-hidden-desktop jb-aside-mobile-toggle\" aria-label=\"Toggle sidebar\"><span class=\"icon\"><i class=\"mdi mdi-forwardburger mdi-24px\"></i></span></a></div><div class=\"navbar-brand is-right\"><a class=\"navbar-item is-hidden-desktop jb-navbar-menu-toggle\" data-target=\"navbar-menu\" aria-label=\"Toggle menu\"><span class=\"icon\"><i class=\"mdi mdi-dots-vertical\"></i></span></a></div><div class=\"navbar-menu fadeIn animated faster\" id=\"navbar-menu\"><div class=\"navbar-end\"><div class=\"navbar-item has-dropdown has-dropdown-with-icons has-user-avatar is-hoverable has-divider\"><a class=\"navbar-link is-arrowless\"><div class=\"is-user-avatar\"><img src=\"https://avatars.dicebear.com/v2/initials/john-doe.svg\" alt=\"John Doe\"></div><div class=\"is-user-name\"><span>John Doe</span></div><span class=\"icon\"><i class=\"mdi mdi-chevron-down\"></i></span></a><div class=\"navbar-dropdown\"><a class=\"navbar-item\"><span class=\"icon\"><i class=\"mdi mdi-account\"></i></span> <span>My Profile</span></a> <a class=\"navbar-item\"><span class=\"icon\"><i class=\"mdi mdi-settings\"></i></span> <span>Settings</span></a><hr class=\"navbar-divider\"><a class=\"navbar-item\"><span class=\"icon\"><i class=\"mdi mdi-logout\"></i></span> <span>Log out</span></a></div></div><a class=\"navbar-item has-divider is-desktop-icon-only\" href=\"/about\"><span class=\"icon\"><i class=\"mdi mdi-help-circle-outline\"></i></span> <span>About</span></a> <a class=\"navbar-item is-desktop-icon-only\"><span class=\"icon\"><i class=\"mdi mdi-logout\"></i></span> <span>Log out</span></a></div></div></nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
